/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_haiersmart_sfcontrol_service_powerctl_SerialPort */

#ifndef _Included_com_haiersmart_sfcontrol_service_powerctl_SerialPort
#define _Included_com_haiersmart_sfcontrol_service_powerctl_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_haiersmart_sfcontrol_service_powerctl_SerialPort
 * Method:    SerialOpen
 * Signature: (Ljava/lang/String;I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_haiersmart_sfcontrol_service_powerctl_SerialPort_SerialOpen
        (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_haiersmart_sfcontrol_service_powerctl_SerialPort
 * Method:    SerialClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_haiersmart_sfcontrol_service_powerctl_SerialPort_SerialClose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
